kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: coronavirus-map
#  namespace: covid-map
  selfLink: >-
    /apis/build.openshift.io/v1/namespaces/covid-map/buildconfigs/coronavirus-map
#   uid: da2abea7-1099-4a34-8248-ff3e2f22c51d
#  resourceVersion: '734286'
#  creationTimestamp: '2020-06-12T04:38:00Z'
  labels:
    app: coronavirus-map
    app.kubernetes.io/component: coronavirus-map
    app.kubernetes.io/instance: coronavirus-map
    app.kubernetes.io/name: modern-webapp
    app.kubernetes.io/part-of: coronavirus-map-app
    app.openshift.io/runtime: modern-webapp
    app.openshift.io/runtime-version: 10.x
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/thoward-rh/coronavirus-map'
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'coronavirus-map:latest'
  resources: {}
#  successfulBuildsHistoryLimit: 5
#  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'modern-webapp:10.x'
      env:
        - name: OUTPUT_DIR
          value: /public
        - name: YARN_ENABLED
          value: 'true'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/thoward-rh/coronavirus-map'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: coronavirus-map-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: coronavirus-map-github-webhook-secret
#    - type: ImageChange
#      imageChange:
#        lastTriggeredImageID: >-
#          image-registry.openshift-image-registry.svc:5000/openshift/modern-webapp@sha256:eb672caddbf6f1d2283ecc2e7f69142bd605f5a0067c951dd9b829f29343edc4
    - type: ConfigChange
  runPolicy: Serial
#status:
#  lastVersion: 2
